// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flygipvkfzlqelthblxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZseWdpcHZrZnpscWVsdGhibHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Nzk3MzAsImV4cCI6MjA1ODQ1NTczMH0.EOpxEG1kykq7kY1HtbPAlK1aXD5ZNG3UaA9W-d2ZSwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);